### ISSUE TITLE
License available?

### ISSUE THREAD

**Issue by dennisumlaut** [hichamjanati/debiased-ot-barycenters#1]
Hello, 

first of all, thank you very much for your repository. It was very useful for our project in which we need a fast method to calculate an approximation of the wasserstein barycenters. 
But I couldn't find any license information for your code. Is it possible to get a license to use your code our project?

Best regards
Dennis

**Comment by hichamjanati** [comment]
Hi @dennisumlaut, glad you find this useful. I've added a license now, you may use this code in your project.
